config/routes.rb
WildfireApp::Application.routes.draw do

  resources :wildfires do
    collection do
    get :results
    get :search 
    end

    member do 
      patch :change_death_toll
    end

    resources :locations do
      collection do
      get :results
      get :search
      get :download_fire_zone
    end

    end
  end

  

 resources :locations do
      member do 
      get :download_fire_zone
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :wildfire
	
	mount_uploader :fire_zone, FireZoneUploader
end

app/models/wildfire.rb
class Wildfire < ActiveRecord::Base
		has_many :locations


	# def self.search(search)
 #  if search
 #    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
 #  else
 #    find(:all)
 #  end
 # end

 ##scopes ##
	# scope :bigwildfires -> { where('acres_burned >= ?', 100,000)}
	scope :casualties, -> {where(death_toll: false )	}
	scope :with_acres_burned, -> (acres_burned) { where('acres_burned = ?', acres_burned)}


	def self.with_acres_burned(acres_burned)
		# if acres_burned.blank? - i could do logic in here if i want
		where('locations.acres_burned LIKE ?', acres_burned)
	end

	def self.search(params)
		# debugger
		name = params[:name]
		acres_burned = params[:acres_burned]
		


		search = Wildfire.all


		# if acres_burned.present?
  #   	search = search.with_acres_burned(acres_burned)
  #   end

    # if acres_burned.present?
    # 	search = search.joins(:locations).where('locations.state LIKE ?',"%#{name}%")
    # end

    if name.present?
    	# search = search.where('name LIKE ?', "%#{name}%")
    	search = search.joins(:locations).where('locations.city LIKE ?', "%#{name}%")
		end

		search
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def index
		@locations = Location.all
	end

	def new
		@new_location = Location.new
	end

	def create
		@new_location = Location.new(location_params)
		if @new_location.save
		redirect_to locations_path
	end
end

	
	def show
		@location = Location.find(params[:id])
	end

	def download_fire_zone
		@location = Location.find(params[:id])
		file = @location.fire_zone
		send_file file.path
	end

	private

	def location_params
		params.require(:location).permit!
	end
end

app/controllers/wildfires_controller.rb
class WildfiresController < ApplicationController

	def index
		@wildfires = Wildfire.all
	end

	def new
		@new_fire = Wildfire.new
	end

	def create
		@new_fire = Wildfire.new(wildfire_params)
		if @new_fire.save
			redirect_to wildfires_path  
		else
			redirect_to new_fire_path
		end
	end
	
	def change_death_toll
		@wildfire = Wildfire.find(params[:id])

		if @wildfire.death_toll
			val = "yes"
	  else
			val = "no"
	  end
	  @wildfire.update_attributes(:death_toll => val)
		redirect_to wildfires_path
	end

	# def search
	# 	# @search_results = Wildfire.joins(:locations).where(:conditions => {'name LIKE ?' => "%#{search}%"}).all
	# 	@search_results = Wildfire.search(params[:search])
	# 	render results_wildfires_path
 #  end

 #get "/doctors/search"
	def search
		
		@wildfires = Wildfire.search(params[:search])
		# render search_wildfires_path
  end


	def results
		@search_results
	end

	def download_fire_zone
		@location = Location.find(params[:id])
		file = @location.fire_zone_path
		send_file file.path
	end


	private

	def wildfire_params
		params.require(:wildfire).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/wildfires_helper.rb
module WildfiresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Store Two Demo</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

 
  </head>

  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <img class="" src="http://www.hillslist.info/resources/Garage-Sale-(300).png" alt="" />
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Wild Fire APP!</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li> <a href="/wildfires">ALL WILDFIRES</a></li>
            <li> <a href="/locations">ALL LOCATIONS</a></li>
            <li> <a href="/wildfires/new">NEW WILD FIRE</a></li>
            <li> <a href="/locations/new">NEW LOCATIONS</a></li>
           

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

	<!-- +++++ Welcome Section +++++ -->
	<%= yield %>
	
	
	
			
			</div>
		
		</div>
	</div>

  </body>
</html>

app/views/locations/index.html.haml
.container
	.container
		.searchbar
			%br
			= form_tag search_wildfires_path, method: "get" do
				= label_tag "Search By Name"
				= text_field_tag 'search[name]'
				= select_tag 'search[acres_burned]', options_for_select(Wildfire.pluck(:acres_burned)), include_blank: true
				= submit_tag "SEARCH"


%h3 All the locations

- @locations.each do |d|
	%h1
		%li
			%p
				City:
				= d.city
				%br
				State:
				= d.state
				%br
				Wild Fire ID:
				= d.wildfire_id
				= d.id
				%img
					= image_tag d.fire_zone.url
				
	
%br

app/views/locations/new.html.haml
.container
	.container
		.searchbar
			%br
			= form_tag search_wildfires_path, method: "get" do
				= label_tag "Search By Name"
				= text_field_tag 'search[name]'
				= select_tag 'search[acres_burned]', options_for_select(Wildfire.pluck(:acres_burned)), include_blank: true
				= submit_tag "SEARCH"
				%br
				%br

= form_for @new_location do |f|
	= f.label :city
	= f.text_field :city

	= f.label :state
	= f.text_field :state

	= f.label :id_number
	= f.number_field :wildfire_id
	= f.file_field :fire_zone
	- f.hidden_field :fire_zone
	= f.label :Date
	= f.select :wildfire_id, Wildfire.all.collect {|d| [d.happened, d.id ]}
	= f.submit

	/ = f.label :State
	/ = f.select :wildfire_id, Location.all.collect {|d| [d.city, d.id ]}

	/ = f.label :Name
	/ = f.select :wildfire_id, Wildfire.all.collect {|d| [d.name, d.id ]}

	

app/views/locations/show.html.haml
%h1
	%li
		%p
			City:
			= @location.city
			%br
			State:
			= @location.state
			%br
			Wild Fire ID:
			= @location.wildfire_id
			= @location.id
			%br
			= link_to "Download Photo", download_fire_zone_location_path
			%img
				= image_tag @location.fire_zone.url
				

/ = link_to "location", @download_fire_zone_path
/ = image_tag @location.fire_zone.url

app/views/wildfires/index.html.haml
.container
	.container
		.searchbar
			%br
			= form_tag search_wildfires_path, method: "get" do
				= label_tag "Search By Name"
				= text_field_tag 'search[name]'
				= select_tag 'search[acres_burned]', options_for_select(Wildfire.pluck(:acres_burned)), include_blank: true
				= submit_tag "SEARCH"
				


/ = form_tag search_wildfires_path, :method => 'get' do
/ 	= text_field_tag :search, params[:search]
/ 	= submit_tag "Search", :name => nil

%h3 Wildfires List
= button_to "add wildfire", new_wildfire_path, method: "get"

- @wildfires.each do |d|
	%h1
		%p
			Name:
			= d.name
			%br
			Date it Occured:
			= d.happened
			%br
			Has Everything Been Repaired?
			= d.death_toll
			%br
			Acres Burned?
			= d.acres_burned
			%br
			ID
			= d.id
			%br
			= link_to "Change to Yes Everything Been Repaired", change_death_toll_wildfire_path(d), method: "patch"
			%br
			%br



	

		

app/views/wildfires/new.html.haml
%h1
	= form_for @new_fire, url: wildfires_path do |f|
		%p
			= f.label :name
			= f.text_field :name
			%br
			= f.label :happened
			= f.text_field :happened
			%br
			= f.label :acres_burned
			= f.text_field :acres_burned
			%br
			%l Fatalities?
			= f.label "Yes"
			= f.radio_button :death_toll, "yes"
			= f.label "No"
			= f.radio_button :death_toll, "no"

			%br
			= f.submit

app/views/wildfires/results.html.haml
%h1 All the wildfires

- @search_results.each do |d|
	Name:
	= d.name
	%br
	Date it Occured:
	= d.happened
	%br
	Where there Deaths?
	= d.death_toll
	%br
	%br



		

app/views/wildfires/search.html.haml
.container
	.container
		.searchbar
			%br
			= form_tag search_wildfires_path, method: "get" do
				= label_tag "Search By Name"
				= text_field_tag 'search[name]'
				= select_tag 'search[acres_burned]', options_for_select(Wildfire.pluck(:acres_burned)), include_blank: true
				= submit_tag "SEARCH"

%h3 All the wildfires

- @wildfires.each do |d|
	%li
		%p
		Name:
		= d.name
		%br
		Date it Occured:
		= d.happened
		%br
		Where there Deaths?
		= d.death_toll
		- d.acres_burned
		%br
		ID
		= d.id
		%br
		= link_to "Change to Yes Everything Been Repaired", change_death_toll_wildfire_path(d), method: "patch"

		- d.locations.each do |l|
			%br
			City:
			= l.city
			%br
			State:
			= l.state
			/ = link_to "Download Photo", download_fire_zone_location_path
			/ %img
			/ 	= image_tag @location.fire_zone.url

		
	